### ISSUE TITLE
Add style for scrollbar

### ISSUE THREAD

**Issue by ainulbedjo** [gattigaga/schemator#3]
just add some style to scrollbar, idk.. its just disgust me lol

<img src="https://scontent.fsub3-1.fna.fbcdn.net/v/t1.0-9/40995543_956244287912953_9093054680325423104_n.jpg?_nc_cat=0&_nc_eui2=AeHYJmi_g3wcylzbK8yvN13mBde4W-D2y7N1E_Fm0rMFy_En3zhRHn7Rec3tz1UW_dR6Aiq8-bIpQZtpzsoxOuC6k0eSCCmVRcipKKTId1ucuRWsn0apfvTOlweog7l_sr8&oh=5ef454cf970f4e9b89e934a21c770b91&oe=5C3B7E58" style="width: 200px; height: 200px;" />

i'm just add this to index.html

`

    <style>
      ::-webkit-scrollbar-corner {
        background: #3e4142;
      }
      ::-webkit-scrollbar-thumb {
        background: #515354;
      }
      ::-webkit-scrollbar {
        width: 10px;
      }
    </style>
`

**Comment by gattigaga** [comment]
That was my plan for the next release...
Thanks for your attention... :+1:

**Comment by gattigaga** [comment]
That was my plan for the next release...
Thanks for your attention... :+1:
